#!/bin/sh
# Xsetup - run as root before the login dialog appears

pacman -Q nvidia
# Check if the 'nvidia' package is installed
if [ "$?" == 0 ]; then
  # Check if we are running the 'linux' kernel
  if [[ $(uname -r) == *-arch* ]]; then
    xrandr --setprovideroutputsource modesetting NVIDIA-0
    xrandr --auto
    xrandr --dpi 96
  fi
fi

pacman -Q nvidia-lts
# Check if the 'nvidia' package is installed
if [ "$?" == 0 ]; then
  # Check if we are running the 'linux' kernel
  if [[ $(uname -r) == *-lts ]]; then
    xrandr --setprovideroutputsource modesetting NVIDIA-0
    xrandr --auto
    xrandr --dpi 96
  fi
fi
